name: Binder
on:
  push:
    branches: [ master, test-* ]
    tags: [ v* ]
  workflow_dispatch:

jobs:
  create-mybinder-cache:
    runs-on: ubuntu-latest
    steps:
    - name: Cache Binder build on MyBinder
      uses: jupyterhub/repo2docker-action@master
      with:
        NO_PUSH: true
        MYBINDERORG_TAG: ${{ github.event.ref }}